### ISSUE TITLE
Logfile option without write access

### ISSUE THREAD

**Issue by davidelbert** [openmsi/openmsistream#55]
OpenMSIStream fails if it has read-only access to the drive because it can't write the log file. We ran into this at Cornell for the first time streaming out of a network drive mount.  Talked to Tyrel and the suggestion is making the logfile directory configurable independent of the datafile directory so you can write the log to the local disk where you have RW permissions.

**Comment by eminizer** [comment]
Working on this today; there's already an option for this that I just need to propagate through to the command line arguments. I'll be able to add it for anything that has a Logger.
